export const $ = (id) => document.getElementById(id);

export function on(id, type, handler) {
  const el = $(id);
  if (el) el.addEventListener(type, handler);
  return el;
}

export function createUIRefs() {
  return {
    canvas: $('sceneCanvas'),
    viewport: $('viewport'),
    statusEl: $('status'),
    brushPreview: $('brushPreview'),
    objectList: $('objectList'),
    objectName: $('objectName'),
    dimX: $('dimX'),
    dimY: $('dimY'),
    dimZ: $('dimZ'),
    lockAspect: $('lockAspect'),
    snapGrid: $('snapGrid'),
    gridSize: $('gridSize'),
    sculptMode: $('sculptMode'),
    brushRadius: $('brushRadius'),
    brushStrength: $('brushStrength'),
    smoothToolOptions: $('smoothToolOptions'),
    smoothPreserveVolume: $('smoothPreserveVolume'),
    smoothTangent: $('smoothTangent'),
    creaseToolOptions: $('creaseToolOptions'),
    creasePinch: $('creasePinch'),
    creaseDepth: $('creaseDepth'),
    negative: $('negative'),
    clay: $('clay'),
    accumulate: $('accumulate'),
    thinSurface: $('thinSurface'),
    lockPosition: $('lockPosition'),
    symmetry: $('symmetry'),
    symmetryY: $('symmetryY'),
    symmetryZ: $('symmetryZ'),
    dynamicTopology: $('dynamicTopology'),
    dynamicTopoEdge: $('dynamicTopoEdge'),
    paintColor: $('paintColor'),
    paintRadius: $('paintRadius'),
    paintOpacity: $('paintOpacity'),
    baseColor: $('baseColor'),
    metalness: $('metalness'),
    roughness: $('roughness'),
    textureInput: $('textureInput'),
    modelInput: $('modelInput'),
    shapeImageInput: $('shapeImageInput'),
    shapeSourcePreview: $('shapeSourcePreview'),
    shapeBinaryPreview: $('shapeBinaryPreview'),
    shapeVectorPreview: $('shapeVectorPreview'),
    shapeThreshold: $('shapeThreshold'),
    shapeThresholdValue: $('shapeThresholdValue'),
    shapeNoiseArea: $('shapeNoiseArea'),
    shapeNoiseAreaValue: $('shapeNoiseAreaValue'),
    shapeSmoothness: $('shapeSmoothness'),
    shapeSmoothnessValue: $('shapeSmoothnessValue'),
    shapeSimplify: $('shapeSimplify'),
    shapeSimplifyValue: $('shapeSimplifyValue'),
    shapeInvert: $('shapeInvert'),
    shapeLockAspect: $('shapeLockAspect'),
    shapeWidth: $('shapeWidth'),
    shapeHeight: $('shapeHeight'),
    shapeDepth: $('shapeDepth'),
    shapeBevel: $('shapeBevel'),
    shapeBevelValue: $('shapeBevelValue'),
    shapeRefreshBtn: $('shapeRefreshBtn'),
    shapeGenerateBtn: $('shapeGenerateBtn'),
    shapeDownloadSvgBtn: $('shapeDownloadSvgBtn'),
    shapeInfo: $('shapeInfo'),
    stlFormat: $('stlFormat'),
    inspectorToggle: $('inspectorToggle'),
    wireframeToggle: $('wireframeToggle'),
    viewMode: $('viewMode'),
    meshStats: $('meshStats'),
    subdivideMeshBtn: $('subdivideMeshBtn'),
    softRemeshBtn: $('softRemeshBtn'),
    reduceMeshBtn: $('reduceMeshBtn'),
    relaxMeshBtn: $('relaxMeshBtn'),
    meshQuality: $('meshQuality'),
    selectionSummary: $('selectionSummary'),
    activeToolName: $('activeToolName'),
    activeToolIcon: $('activeToolIcon'),
    workspaceHint: $('workspaceHint'),
    hudPrimary: $('hudPrimary'),
    hudSecondary: $('hudSecondary'),
    helpDialog: $('helpDialog'),
    brushRadiusValue: $('brushRadiusValue'),
    brushStrengthValue: $('brushStrengthValue'),
    creasePinchValue: $('creasePinchValue'),
    creaseDepthValue: $('creaseDepthValue'),
    dynamicTopoValue: $('dynamicTopoValue'),
    paintRadiusValue: $('paintRadiusValue'),
    paintOpacityValue: $('paintOpacityValue'),
    metalnessValue: $('metalnessValue'),
    roughnessValue: $('roughnessValue')
  };
}
